### ISSUE TITLE
Q1. data_type

### ISSUE THREAD

**Issue by dolzi** [kyohoonsim/must-know-python#1]
Q1. "i Am a boY"라는 문자열을 문자열 객체의 어떤 메서드를 사용하여 "I am a boy"로 변환해서 콘솔에 출력할 것.

[코드 캡처]
[결과 캡처]
or
[코드 캡처 / 결과 캡처]

**Comment by echoe1009** [comment]
print("i Am a boY".capitalize())

![image](https://github.com/kyohoonsim/must-know-python/assets/134114538/3d364a6d-eb99-4976-9964-5bbcbb0154d2)

**Comment by hungrywoo** [comment]
print("i Am a boY".capitalize())
![image](https://github.com/kyohoonsim/must-know-python/assets/96517936/e3710821-e8a8-49bc-acce-65b73126b57a)

**Comment by jjjjjjye** [comment]
<img width="185" alt="스크린샷 2023-06-22 222019" src="https://github.com/kyohoonsim/must-know-python/assets/134114728/11b86354-1e03-41ea-8ddb-b9be139b744c">

**Comment by xinnazim** [comment]
print("i Am a boY".capitalize())
![data_type py - kusf_python - Visual Studio Code 2023-06-22 오후 10_21_08](https://github.com/kyohoonsim/must-know-python/assets/127488424/593c9321-3569-4cb8-b77d-6359e0d7ac29)

**Comment by KUSFTWOO** [comment]
a = "i Am a boY"

print(dir(a))

print(a.capitalize())
![image](https://github.com/kyohoonsim/must-know-python/assets/134114521/1f097d68-72e9-4f96-8342-5d35bf09e88f)

**Comment by dhEhdod** [comment]
print("i Am a boY".capitalize())

![image](https://github.com/kyohoonsim/must-know-python/assets/104903908/4024d90f-bb79-4307-a3d6-ba89173283d3)

**Comment by BAEKDONGSEOK** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/134114842/8b6bf14e-8fb9-4cd2-8070-3127aecb4ef0)

**Comment by monimanimo** [comment]
name = "i Am a boY"
print(name.capitalize())
![image](https://github.com/kyohoonsim/must-know-python/assets/134114554/82114aa5-35c1-4bf3-bfa2-655dcc79f344)

**Comment by yibeeeen** [comment]
print('i Am a boY'.capitalize())
<img width="478" alt="image" src="https://github.com/kyohoonsim/must-know-python/assets/134114534/6822cfe9-3059-45ed-8840-db24f99a19a2">

**Comment by YelynYoo** [comment]
a = 'i Am a boY'
print(a.capitalize())

![image](https://github.com/kyohoonsim/must-know-python/assets/134114507/f6daf302-eb7f-49a0-9eff-5cbbb7a97d24)

**Comment by SHINZIMIN** [comment]
print("i Am a boY".capitalize())

![image](https://github.com/kyohoonsim/must-know-python/assets/134114647/8c6a7ab8-4237-480a-a2b7-c02316de9a31)

**Comment by WooJHo** [comment]
print('i Am a boY'.capitalize())
![image](https://github.com/kyohoonsim/must-know-python/assets/134114659/d68646bd-7898-45ed-be1a-9998a78229e3)

**Comment by expediore** [comment]
a = "i Am a boY"
a = a.lower()
b = a.split()
b[0] = b[0].upper()
print(*b)
![image](https://github.com/kyohoonsim/must-know-python/assets/124579263/4267ba4d-df55-44df-a330-b01f93429099)
