### ISSUE TITLE
Q2. conditional_statement

### ISSUE THREAD

**Issue by dolzi** [kyohoonsim/must-know-python#2]
Q2. 사용자가 3 또는 4 또는 5를 입력하면 "봄"이라고 출력하고, 6 또는 7 또는 8을 입력하면 "여름"이라고 출력하고, 9 뚀는 10 또는 11을 입력하면 "가을"이라고 출력하고, 12 또는 1 또는 2를 입력하면 "겨울"이라고 출력하는 프로그램을 만드시오.

그 외의 숫자를 입력하면 "잘못된 입력"을 출력할 것!

input() 함수와 if 문을 사용할 것!

[코드 캡처]
[결과 캡처]
or
[코드 캡처 / 결과 캡처]

**Comment by dhEhdod** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/104903908/1576ec12-5228-42ef-9415-f07a11de86dc)

**Comment by YelynYoo** [comment]
a= int(input('월을 입력하세요:'))
if a == 1 or 2:
    print('겨울')
elif a == 3 or 4 or 5:
    print('봄')
elif a == 6 or 7 or 8:
    print('여름')
elif a == 10 or 11:
    print('가을')

![image](https://github.com/kyohoonsim/must-know-python/assets/134114507/bc63aea5-afac-457e-b8dc-124abfff39d2)

**Comment by hungrywoo** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/96517936/51526b90-5ffd-4451-8a08-b16909d8a35b)
![image](https://github.com/kyohoonsim/must-know-python/assets/96517936/69978554-a2e9-4717-99a1-f6d9a2a9cb03)

**Comment by KUSFTWOO** [comment]
month = int(input("몇 월인지 입력하세요>>"))

if month == 3 or month == 4 or month == 5 :
    print("봄")
elif month == 6 or month == 7 or month == 8 :
    print("여름")
elif month == 9 or month == 10 or month == 11 :
    print("가을")
elif month == 12 or month == 1 or month == 2 :           
    print("겨울")
else:
    print("잘못된 입력")
![image](https://github.com/kyohoonsim/must-know-python/assets/134114521/8bc8e280-0e29-43ab-838d-5dbf249c4696)

**Comment by monimanimo** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/134114554/a9c8a391-2994-4967-a0a0-2654509599a0)
![image](https://github.com/kyohoonsim/must-know-python/assets/134114554/b4b680c3-c29c-498c-b917-a4d162cf65e4)

**Comment by echoe1009** [comment]
a= int(input('월을 입력하세요:'))

if a == 1 or 2:
    print('겨울')
elif a == 3 or 4 or 5:
    print('봄')
elif a == 6 or 7 or 8:
    print('여름')
elif a == 10 or 11:
    print('가을')

![image](https://github.com/kyohoonsim/must-know-python/assets/134114538/0333da68-2e5c-40ee-9afb-26a56031cfb4)

**Comment by jjjjjjye** [comment]
<img width="338" alt="2" src="https://github.com/kyohoonsim/must-know-python/assets/134114728/e9dc46f1-0164-4d98-940e-d13cdb2a58bf">

**Comment by WooJHo** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/134114659/4a0a0982-7466-4491-8408-28b46c92b2b6)
![image](https://github.com/kyohoonsim/must-know-python/assets/134114659/1a282192-e354-44a8-821e-e1767a1367b3)

**Comment by YelynYoo** [comment]
a= int(input('월을 입력하세요:'))

if a == 1 or a == 2:
    print('겨울')
elif a == 3 or a == 4 or a == 5:
    print('봄')
elif a == 6 or a == 7 or a == 8:
    print('여름')
elif a == 10 or a == 11:
    print('가을')
else:
    print('잘못된 입력')

![image](https://github.com/kyohoonsim/must-know-python/assets/134114507/ef2179e2-03ba-4a00-9f91-fb3b97d23da2)

**Comment by yibeeeen** [comment]
month = int(input())
if month == 3 or month == 4 or month == 5 :
    print('봄')
elif month == 6 or month == 7 or month == 8 :
        print ('여름')
elif month == 9 or month == 10 or month == 11:
            print('가을')
else : print('잘못된 입력')
<img width="1440" alt="스크린샷 2023-06-22 오후 10 20 42" src="https://github.com/kyohoonsim/must-know-python/assets/134114534/a8431a51-3a09-4300-b9e2-08f123f79259">
<img width="505" alt="image" src="https://github.com/kyohoonsim/must-know-python/assets/134114534/3f6666c2-4231-429c-bdd3-1ad7c115e885">

**Comment by yibeeeen** [comment]
month = int(input())
if month == 3 or month == 4 or month == 5 :
    print('봄')
elif month == 6 or month == 7 or month == 8 :
        print ('여름')
elif month == 9 or month == 10 or month == 11:
            print('가을')
else : print('잘못된 입력')

<img width="458" alt="image" src="https://github.com/kyohoonsim/must-know-python/assets/134114534/668a2aac-2e69-4740-a704-94c9749996d6">
<img width="503" alt="image" src="https://github.com/kyohoonsim/must-know-python/assets/134114534/579266db-9ec3-467d-8c47-366376d2922f">

**Comment by BAEKDONGSEOK** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/134114842/14685dd0-82c0-47cb-9173-40da03a8ce2f)

**Comment by SHINZIMIN** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/134114647/34695354-518f-4879-9c52-20eda4a1037c)

**Comment by yibeeeen** [comment]
<img width="497" alt="스크린샷 2023-06-22 오후 10 59 56" src="https://github.com/kyohoonsim/must-know-python/assets/134114534/4c36081e-c034-49df-b125-ab5dbf5d1122">

**Comment by expediore** [comment]
month = int(input("1~12 사이의 월 숫자를 입력하시오. "))

if (3 <= month < 6) :
    print('봄')

elif (6 <= month < 9) :
    print('여름')

elif (9 <= month < 12) :
    print('가을')

elif (1 <= month < 3) or (month == 12) :
    print('겨울')

else :
    print('잘못된 입력')

![image](https://github.com/kyohoonsim/must-know-python/assets/124579263/8d6be27d-217b-450d-b4f4-cb66eb438808)
