### ISSUE TITLE
Q3. iteration_statement

### ISSUE THREAD

**Issue by dolzi** [kyohoonsim/must-know-python#3]
Q3. 주인의 명령에 따라 강아지를 돌보는 로봇을 프로그래밍해보자.
사용자가 1을 누르면, "먹이를 줍니다."가 콘솔에 출력되게 한다.
프로그램은 종료되지 않은 상태에서 다음 명령을 기다린다.
사용자가 2를 누르면, "놀아 줍니다."가 콘솔에 출력된다.
사용자가 3을 누르면, "산책을 시킵니다.", 4를 누르면 "목욕을 시킵니다."가 출력된다.
사용자가 q를 누를 때까지 이 프로그램은 종료하지 않는다.
프로그램 종료시 강아지의 행복 점수를 출력한다.
먹이를 주면 강아지 행복 점수가 +5 된다.
놀아주면 강아지 행복 점수가 +7 된다.
산책을 시키면 행복 점수가 +10 된다.
목욕을 시키면 행복 점수가 +3 된다.
최대한 예쁘게 만들어볼 것.

[코드 캡처]
[결과 캡처]
or
[코드 캡처 / 결과 캡처]

**Comment by dhEhdod** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/104903908/3dda6f67-f3bd-4da5-b0d5-f1e7add4d140)
![image](https://github.com/kyohoonsim/must-know-python/assets/104903908/acce6ed3-dd3a-425f-bcdf-0f8b66ebc0a7)

**Comment by WooJHo** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/134114659/5e7a1a3c-a4b0-44cd-be73-b2393e319341)
![image](https://github.com/kyohoonsim/must-know-python/assets/134114659/95be142d-1805-469b-b054-a2e6c849bd2d)

**Comment by hungrywoo** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/96517936/3808220d-793b-4647-9ee4-42a89794f7ef)
![image](https://github.com/kyohoonsim/must-know-python/assets/96517936/754bff20-1185-4e3e-9f0d-230eade078fd)

**Comment by KUSFTWOO** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/134114521/dcadbfae-9c18-402c-aaec-fdd4b3ed9a99)

**Comment by jjjjjjye** [comment]
<img width="376" alt="3" src="https://github.com/kyohoonsim/must-know-python/assets/134114728/20a8aabb-c19f-4a81-87fe-c803de2fd112">

**Comment by monimanimo** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/134114554/fe088d9f-6f4f-4bac-9622-2fa2a113de6e)
![image](https://github.com/kyohoonsim/must-know-python/assets/134114554/8523bca8-b82d-460c-aa5c-08e8dad631b9)

**Comment by SHINZIMIN** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/134114647/f76310b2-84eb-4842-8244-cf516457fdd6)


![image](https://github.com/kyohoonsim/must-know-python/assets/134114647/c5ac079e-1ff0-426f-813f-e46c2d9ec3ac)

**Comment by expediore** [comment]
happy_score = 0

while True :
    order = input("1, 2, 3, 4 중에 선택하시오.(종료는 q) ")
    if (order == '1') :
        print('먹이를 줍니다.')
        happy_score += 5
    elif (order == '2') :
        print('놀아 줍니다.')
        happy_score += 7
    elif (order == '3') :
        print('산책을 시킵니다.')
        happy_score += 10
    elif (order == '4') :
        print('목욕을 시킵니다.')
        happy_score += 3
    elif (order == 'q') :
        print(happy_score)
        break


![image](https://github.com/kyohoonsim/must-know-python/assets/124579263/7bc05ea5-2e13-4df7-ab1f-7a9161655c02)
