### ISSUE TITLE
Q4. function

### ISSUE THREAD

**Issue by dolzi** [kyohoonsim/must-know-python#4]
Q4. 인사를 하는 사람의 이름(A)과 인사를 받는 사람 이름(B)을 매개변수로 전달받아 콘솔에 "A가 B에게 인사를 합니다"를 출력해주는 함수를 만들 것. 독스트링과 타입 어노테이션을 활용할 것.

[코드 캡처]
[결과 캡처]
or
[코드 캡처 / 결과 캡처]

**Comment by hungrywoo** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/96517936/8e5fdba5-7234-4adf-aff7-98e4848e7192)
![image](https://github.com/kyohoonsim/must-know-python/assets/96517936/db9eff5c-a912-4b9c-ac84-1a422dad4c8f)

**Comment by monimanimo** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/134114554/26c77357-c203-497c-9928-25b0d36e7bf8)

![image](https://github.com/kyohoonsim/must-know-python/assets/134114554/fdb70ee9-359b-4f65-9950-4960b6d8ee5c)

**Comment by dhEhdod** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/104903908/85d4bc59-3e0c-4320-879d-6a14f270e7ec)
![image](https://github.com/kyohoonsim/must-know-python/assets/104903908/d82ea2a3-cf8e-41b9-b803-7b8d45982cb1)

**Comment by KUSFTWOO** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/134114521/f80221bb-1aa4-42a0-a83e-0c9f3f63f62f)

**Comment by WooJHo** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/134114659/256ace8a-5e5a-4ca2-a169-3dddd84e9923)
![image](https://github.com/kyohoonsim/must-know-python/assets/134114659/58422176-4f2d-4f78-9618-a2ee69ea6cf1)

**Comment by jjjjjjye** [comment]
<img width="298" alt="4" src="https://github.com/kyohoonsim/must-know-python/assets/134114728/2605495e-804d-4463-bd95-b369119159bd">

**Comment by yibeeeen** [comment]
<img width="554" alt="image" src="https://github.com/kyohoonsim/must-know-python/assets/134114534/7356952b-19fb-40ea-898e-38457de389a8">
<img width="480" alt="image" src="https://github.com/kyohoonsim/must-know-python/assets/134114534/33edc34e-f223-4b11-938b-9f9bce473f61">

**Comment by expediore** [comment]
def hello (A : str, B : str) -> None:
    '''두 개의 문자열을 매개변수로 받아 문장을 출력
    
    Args:
        A (str) : 인사를 하는 사람
        B (str) : 인사를 받는 사람
        
    Returns:
        None:
    
    '''
    print(f"{A}가 {B}에게 인사를 합니다.")

give = input("인사를 하는 사람의 이름 : ")
take = input("인사를 받는 사람 이름 : ")
hello(give, take)

![image](https://github.com/kyohoonsim/must-know-python/assets/124579263/995d9103-547f-4d8f-98fc-074bdcc2e298)
