### ISSUE TITLE
Q5. class

### ISSUE THREAD

**Issue by dolzi** [kyohoonsim/must-know-python#5]
Q5. 포켓몬 클래스를 하나 만든다.
포켓몬 클래스는 객체를 생성할 때 이름을 전달받는다.
포켓몬 클래스는 자기 이름을 소개하는 메서드를 갖는다.
포켓몬 클래스를 상속 받아서 피카추 클래스, 꼬부기 클래스를 만들 것.
피카추 클래스에는 피카추만의 능력을 메서드로 만들고, 꼬부기 클래스에는 꼬부기만의 능력을 메서드로 추가할 것.
만든 피카추 클래스와 꼬부기 클래스로 각각 1개의 인스턴스를 생성하여 가진 능력을 뽐낼 것.

[코드 캡처]
[결과 캡처]
or
[코드 캡처 / 결과 캡처]

**Comment by KUSFTWOO** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/134114521/3910cc4a-53cf-4b21-bd89-595ab13ab05e)

**Comment by WooJHo** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/134114659/b7ce557d-4e27-4e7d-8eb6-bc24ed046f45)
![image](https://github.com/kyohoonsim/must-know-python/assets/134114659/1d289b90-7a82-43f3-a658-d6ff927895c5)

**Comment by hungrywoo** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/96517936/570efc92-10ac-4b2c-9be5-f020fd7d35e9)
![image](https://github.com/kyohoonsim/must-know-python/assets/96517936/a68db375-017b-43f4-a51a-2cdcae8e3237)

**Comment by monimanimo** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/134114554/b86385a8-a8f0-426a-89bc-77362e5b86d1)
![image](https://github.com/kyohoonsim/must-know-python/assets/134114554/c3166ee8-30be-435a-8092-2a36b34b000e)

**Comment by dhEhdod** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/104903908/4a6b0459-b111-4480-888c-9643f6f75ced)
![image](https://github.com/kyohoonsim/must-know-python/assets/104903908/e4538fbb-3de8-476f-aac2-903efd6cab89)

**Comment by jjjjjjye** [comment]
<img width="413" alt="5" src="https://github.com/kyohoonsim/must-know-python/assets/134114728/4dc79c4c-080e-4a1c-a45d-b0d2333996e7">
