### ISSUE TITLE
Q6. class

### ISSUE THREAD

**Issue by dolzi** [kyohoonsim/must-know-python#6]
Q6. 
- 클래스 하나 정의
- 클래스 상속 받아 2개 또는 3개 클래스 정의
- 그 클래스로 각각 객체 생성 및 활용 

[코드 캡처]
[결과 캡처]
or
[코드 캡처 / 결과 캡처]

**Comment by monimanimo** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/134114554/6cf18032-d352-4068-a8c1-77010a56e0fd)
![image](https://github.com/kyohoonsim/must-know-python/assets/134114554/1130f962-e8dd-40bf-b6ee-d591c701ecb2)

**Comment by monimanimo** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/134114554/bb7a4b6b-4ae1-49d4-967f-ad118ca15a0e)
![image](https://github.com/kyohoonsim/must-know-python/assets/134114554/9d170514-beca-4a22-9141-5d24c2f0d00d)

**Comment by aosdbfc** [comment]
```
class Bank:
    bank_cnt = 0

    def __init__(self, money, dollars, won):
        self.money = money
        self.dollars = dollars
        self.won = won
        Bank.bank_cnt += 1

    def retrieval(self):
        print(f"현금 {self.money}를 인출했습니다.")

    def saving(self):
        print(f"현금 {self.money}를 저축했습니다.")

    def exchange(self):
        print(f"한화 {self.won}만원를 달러 {self.dollars}달러로 환전했습니다.")

    @staticmethod
    def loan(amount):
        print(f"{amount}을 대출받았습니다.")

    @classmethod
    def get_bank_count(cls):
        print(f"은행 계좌 개수: {cls.bank_cnt}")

class OtherBank(Bank):
    def additional_feature(self):
        print("다른 은행의 추가 기능입니다.")


###### Example usage

sinhan = Bank(10000, 100, 1000)
sinhan.saving()
sinhan.retrieval()
sinhan.exchange()

Bank.loan(5000)
Bank.get_bank_count()

other_bank = OtherBank(20000, 200, 2000)
other_bank.additional_feature()

```

![image](https://github.com/kyohoonsim/must-know-python/assets/102851378/f47f524f-cfb5-469f-9fab-15a2233c477a)

**Comment by echoe1009** [comment]
class Football:
    def __init__(self, name, win, draw ,lose):
        self.name = name
        self.win = win
        self.draw = draw
        self.lose = lose
    def intro(self):
        point = self.win*3 + self.draw*1 + self.lose*0
        print(f"이 팀은 {self.name}이고, 이번 시즌 성적은 {self.win}승 {self.draw}무 {self.lose}패 입니다.")
        print(f"현재 승점은 {point}점 입니다.")

        
class Suwon(Football):
    def suwonchant(self):
        print("이 사랑에 후회는 없어")

class Seoul(Football):
    def seoulchant(self):
        print("그대들이 가는길 우리가 지켜주리라")

t1 = Suwon("수원 삼성", 2, 3, 13)
t2 = Seoul("FC서울", 8, 5, 5)

t1.intro()
t1.suwonchant()
print("VS")
t2.intro()
t2.seoulchant()
![image](https://github.com/kyohoonsim/must-know-python/assets/134114538/ead1b61c-e323-4731-8f59-2e50de4c9580)

**Comment by indianaPoly** [comment]
```
class WebsiteFunc:
    login_fail_cnt = 0
    
    def __init__ (self, url: str):
        self.url = url
        print(f"해당 사이트 주소는{self.url}")

    def search(self, word):
        print(f"{word}를 검색합니다.");
        
    def login(self, id:str, password:str):

          def account_lock() :
              print("계정이 잠겼습니다.")

          if (id == "hello" and password == "world") :
            print(f"{self.url}에 로그인을 합니다.")
            return "token"
          else:
            print("로그인에 실패하였습니다")
            WebsiteFunc.login_fail_cnt += 1
            if (WebsiteFunc.login_fail_cnt == 5) :
              account_lock();
    
    @classmethod
    def login_fail(cls):
        cls.login_fail_cnt += 1

    @classmethod
    def account_lock(cls):
        print("계정이 잠겼습니다.")
        cls.login_fail_cnt = 0
        
class Naver(WebsiteFunc):
    def rank(self):
        print("실시간 검색어 순위를 가져옵니다.")

class Daum(WebsiteFunc):
    def kakao_tv(self):
        print("카카오 TV를 보여줍니다.")

print("------------------------------")

web1 = Naver("www.naver.com")
token = web1.login("hello", "world")
if (token == "token") :
  web1.rank()
  web1.search("KUSF")

print("------------------------------")

web2 = Daum("www.daum.net")
token = web2.login("hell", "ro")
token = web2.login("hell", "ro")
token = web2.login("hell", "ro")
token = web2.login("hell", "ro")
token = web2.login("hell", "ro")
if (token == "token") :
    web2.kakao_tv()
    web2.search("KUSF")


print("------------------------------")

web3 = WebsiteFunc("www.google.com")
token = web3.login("hello", "world")
if (token == "token") :
    web3.search("KUSF")
```
<img width="1055" alt="스크린샷 2023-06-24 오전 11 54 24" src="https://github.com/kyohoonsim/must-know-python/assets/95522176/292ed875-0d69-488b-9b21-29d54366a33d">

**Comment by KUSFTWOO** [comment]
class ManCity:
    mancity_cnt = 0
    
    def __init__(self, name, backnum, pos):
        self.name = name
        self.backnum = backnum
        self.pos = pos
        ManCity.mancity_cnt += 1
        
    def team(self):
        print(f"저는 맨체스터 시티 소속입니다.")
        
class Player(ManCity):
    def player(self):
        print(f"제 이름은 {self.name}이고, 저의 등번호는 {self.backnum}번이고, 저의 포지션은 {self.pos}에서 주로 뜁니다.")
    

p1 = Player("필 포든", 47, "LW")
p2 = Player("케빈 더브라위너", 17, "CAM")
p3 = Player("로드리", 16, "CDM")
p4 = Player("에데르송", 1, "GK")

p1.player()
p1.team()

p2.player()
p2.team()

p3.player()
p3.team()

p4.player()
p4.team()

print(f"현재까지 라인업 등록 인원 {ManCity.mancity_cnt}명.")
![image](https://github.com/kyohoonsim/must-know-python/assets/134114521/89fa16a4-4309-4ca6-9ac6-44f41db793cc)

**Comment by JJungEunnn** [comment]
<img width="517" alt="image" src="https://github.com/kyohoonsim/must-know-python/assets/134114685/c40e2b27-551d-4505-a293-081e99281a25">

<img width="291" alt="image" src="https://github.com/kyohoonsim/must-know-python/assets/134114685/56c80abc-1798-468c-bcc7-1a1ffcc3c418">

**Comment by KUSFTWOO** [comment]
class ManCity:
    mancity_cnt = 0
    
    def __init__(self, name, backnum, pos):
        self.name = name
        self.backnum = backnum
        self.pos = pos
        ManCity.mancity_cnt += 1
        
    def team(self):
        print(f"저는 맨체스터 시티 소속입니다.")
        
class Player(ManCity):
    def player(self):
        print(f"제 이름은 {self.name}이고, 저의 등번호는 {self.backnum}번이며, 저의 포지션은 {self.pos}에서 주로 뜁니다.")
    

p1 = Player("필 포든", 47, "LW")
p2 = Player("케빈 더브라위너", 17, "CAM")
p3 = Player("로드리", 16, "CDM")
p4 = Player("에데르송", 1, "GK")

p1.player()
p1.team()

p2.player()
p2.team()

p3.player()
p3.team()

p4.player()
p4.team()

print("=====================================")
print(f"현재까지 라인업 등록 인원 {ManCity.mancity_cnt}명.등록 가능 인원은 {11-ManCity.mancity_cnt}명 입니다.")
![image](https://github.com/kyohoonsim/must-know-python/assets/134114521/860d50a9-50a7-4e06-b09b-5f7dfca04aa8)

**Comment by WooJHo** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/134114659/b38f6ed4-634c-4cf3-bf9c-d86171b601eb)
![image](https://github.com/kyohoonsim/must-know-python/assets/134114659/08954e1b-758a-4cf2-adf1-9028f73b3c8e)

**Comment by WooJHo** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/134114659/f5239153-e512-4608-a13b-be45e216d444)
![image](https://github.com/kyohoonsim/must-know-python/assets/134114659/8fedd176-7e46-4d79-a984-ce779da350fd)

**Comment by hungrywoo** [comment]
```python
class BaseballPlayer:
    def __init__(self, name: str, position: str):
        self.name = name
        self.position = position

    def introduce(self):
        print(f"제 이름은 {self.name}이고, {self.position} 입니다.")
      
class Pitcher(BaseballPlayer):
    def pithcer_type(self, hand: str):
        if hand == "right":
            print("저는 우완 투수 입니다.")
        else:
            print("저는 좌완 투수 입니다.")

class Batter(BaseballPlayer):
    def batter_type(self, hand: str, homerun_cnt: int):
        if hand == "right":
            if homerun_cnt >= 30:
                print("저는 우타자이고, 홈런타자입니다.")
            else:
                print("저는 우타자 입니다.")    
        
        else:
            if homerun_cnt >= 30:
                print("저는 좌타자이고, 홈런타자입니다.")
            else:
                print("저는 좌타자입니다.")    
        

player1 = Pitcher("심교훈", "투수")
player1.introduce()
player1.pithcer_type("right")

player2 = Batter("도준혁", "타자")
player2.introduce()
player2. batter_type("left", 35)

``` 
![image](https://github.com/kyohoonsim/must-know-python/assets/96517936/a997015a-1e11-4245-aa54-bc80a11363ea)

**Comment by Y0nghwan** [comment]
#### 부모 클래스 식당 
#### 자식 클래스 한식, 양식, 일식

class Restaurant:
    def __init__(self, name: str, phonenum: str, made_year: int):
        self.name = name # 상호명
        self.phonenum = phonenum # 가게 전화번호
        self.made_year = made_year # 게시연도
    
    def get_name(self):
        print(f"저희 식당 이름은 {self.name}입니다.")

    def get_phonenum(self):
        print(f"저희 식당 전화번호는 {self.phonenum}입니다.\n위의 번호는 \'-\'없이 입력된 번호입니다.")

    def get_made_year(self):
        if self.made_year > 2000:
            print("저희 식당은 2000년 이후 오픈했습니다.")
        else:
            print("저희 식당은 2000년 이전 오픈했습니다.")

class Korean(Restaurant):
    def issue(self):
        print("배추 가격 인상으로 김치 가격이 올랐습니다. 죄송합니다.")

class Western(Restaurant):
    def no_chopstick(self):
        print("저희 매장엔 젓가락이 없습니다.")
        
class Japanese(Restaurant):
    def fish(self):
        today_fish = input("오늘의 생선을 입력하세요 ")
        print(f"오늘의 생선은 {today_fish}입니다.")

hansot = Korean("한솥", "2139", 1998)
hansot.get_name()
hansot.get_phonenum()
hansot.get_made_year()
hansot.issue()

outback = Western("아웃백", "0423", 2010)
outback.get_name()
outback.get_phonenum()
outback.get_made_year()
outback.no_chopstick()

sushiho = Japanese("스시호", "1234", 2005)
sushiho.get_name()
sushiho.get_phonenum()
sushiho.get_made_year()
sushiho.fish()

<img width="332" alt="image" src="https://github.com/kyohoonsim/must-know-python/assets/98325546/8079015a-f07c-4fa1-acac-a2c182350791">

<img width="239" alt="image" src="https://github.com/kyohoonsim/must-know-python/assets/98325546/b244274d-7fca-463a-9082-54c511158a6d">

**Comment by dhEhdod** [comment]
class Player:
    def __init__(self, name: str, team: str, sport: str, position: str):
        self.name = name
        self.team = team
        self.sport = sport
        self.position = position

    def introduce(self):
        print(f'{self.name}는 {self.sport}선수입니다.')


class Baseball(Player):
    def skill(self, style: str):
        if self.position == '투수' :
            print(f'이 선수는 {self.team} 소속 선수이고 {style} {self.position}입니다.\n')
        else :
            print(f"이 선수는 {self.team} 소속 선수이고 {style} {self.position}입니다.\n")
        
    

class ESports(Player):
    def debut(self, debut: int):
        print(f'이 선수는 {self.team} 선수이고 {debut}년에 데뷔한 {self.position}입니다.\n')


p1 = Baseball('문동주', '한화', '야구', '투수')
p1.introduce()
p1.skill('강속구')

p2 = Baseball('박동원', 'LG', '야구', '타자')
p2.introduce()
p2.skill('홈런')

p3 = ESports('페이커', 'T1', '이스포츠', '미드라이너')
p3.introduce()
p3.debut(2013)

p4 = ESports('기인', 'KT', '이스포츠', '탑라이너')
p4.introduce()
p4.debut(2017)

**Comment by expediore** [comment]
import random

class Pocketmon :
    cnt = 0

    def __init__(self, name, hp, state) :
        self.name = name
        self.hp = hp
        self.state = state

    def introduce(self) :
        print(f'내 이름은 {self.name}이고, 체력은 {self.hp}입니다.')

    def now_hp(self) :
        print(f'{self.name}의 현재 체력은 {self.hp}입니다.')


class Pikachu(Pocketmon) :
      
    def thunderstorm(self) :
        print(f'{self.name}의 번개!')
        pocketmon2.hp -= 70
        cnt = int(random.random() * 100) % 3
        if cnt == 1 :
            print('상대방은 마비 상태가 되었습니다.')
            pocketmon2.state = 1

        
        
class Gobuki(Pocketmon) :
       
    def hydropump(self) :
        if (pocketmon2.state == 1) :
            return 0
        print(f'{self.name}의 하이드로펌프!')
        pocketmon1.hp -= 80
        cnt_2 = int(random.random() * 100) % 4
        if cnt_2 == 1 :
            print('급소에 맞았습니다.')
            pocketmon1.hp -= 80


pocketmon1 = Pikachu("피카추", 200, 0)
pocketmon2 = Gobuki("꼬부기", 250, 0)

pocketmon1.introduce()
pocketmon2.introduce()

pocketmon1.thunderstorm()
pocketmon2.now_hp()

pocketmon2.hydropump()
pocketmon1.now_hp()

![image](https://github.com/kyohoonsim/must-know-python/assets/124579263/63205e86-533b-42c8-ade0-c2bde65b95d5)
![image](https://github.com/kyohoonsim/must-know-python/assets/124579263/8d9acbf0-b97d-4ec8-ada7-772ece0e34b7)
![image](https://github.com/kyohoonsim/must-know-python/assets/124579263/35c8684e-8593-4a25-a9fb-f66097d3cb31)

**Comment by last0331** [comment]
![PQ 6](https://github.com/kyohoonsim/must-know-python/assets/134114710/5d0863fe-d6f7-4df5-a366-3611fafb032f)

![PQ 6-1](https://github.com/kyohoonsim/must-know-python/assets/134114710/8b2d0b40-e004-40f4-9edc-70a43fb86b74)

**Comment by BAEKDONGSEOK** [comment]
class sport:
    def __init__(self, sport, type):
        self.sport = sport
        self.type = type

    def introduce(self):
        print(f"종목이름은 {self.sport}이고, 특징은{self.type}입니다.")

class football(sport):
    def ball (self):
        print("이종목은 공을사용합니다.")

class swim(sport):
    def water(self):
        print("이종목은 공을사용하지않습니다.")


p1 = football("축구","구기종목")
p2 = swim ("수영","수상종목")

p1.introduce()
p1.ball()

p2.introduce()
p2.water()



종목이름은 축구이고, 특징은구기종목입니다.
이종목은 공을사용합니다.
종목이름은 수영이고, 특징은수상종목입니다.
이종목은 공을사용하지않습니다.

**Comment by SHINZIMIN** [comment]
class Major:
    def __init__(self, name : str, college : str, studying : str):
        self.name = name
        self.studying = studying
        self.college = college
        
    def study (self):
        print(f"저희 과는 {self.name}이고, {self.college}소속입니다.  {self.studying} 배웁니다. ")
        

class Korean(Major):
    def language(self):
        print("글을 씁니다.\n")
        
class Engineering(Major): 
    def math (self):
        print("이과입니다.\n")

class Art(Major): 
    def painting(self):
        print("그림 그립니다. ")     
        
p1 = Korean ("국어국문학과", "인문사회대학","국어국문")
p2 = Engineering("산업공학과","기술경영융합대학", "여러가지")
p3 = Art ("디자인과", "조형대학", "미술")

p1.study()
p1.language()

p2.study()
p2.math()

p3.study()
p3.painting()

![image](https://github.com/kyohoonsim/must-know-python/assets/134114647/1524dfe8-c648-49c2-a1b6-40e850723b6c)

**Comment by WooJHo** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/134114659/8cf09cc8-cc2a-46ca-be20-99a89f9451b0)
![image](https://github.com/kyohoonsim/must-know-python/assets/134114659/ce592575-7d44-4e64-86f0-3b4e9941b722)

**Comment by kyohoonsim** [comment]
연대생 없나요 ㅋㅋ
