### ISSUE TITLE
Quiz 1. 문자열 주요 메소드

### ISSUE THREAD

**Issue by dolzi** [kyohoonsim/must-know-python#7]
[문자열 주요 메소드](https://github.com/kyohoonsim/must-know-python/blob/master/01_%EC%9E%90%EB%A3%8C%ED%98%95.md#%EB%AC%B8%EC%9E%90%EC%97%B4-%EC%A3%BC%EC%9A%94-%EB%A9%94%EC%86%8C%EB%93%9C)

quiz 1-1. "i Am a boY"라는 문자열을 문자열 객체의 어떤 메서드를 사용하여 "I am a boy"로 변환해서 콘솔에 출력할 것.

quiz 1-2. 문자열 객체의 어떤 메서드를 사용하여 'banana|strawberry|watermelon' 문자열을 각 과일 이름을 요소로 담은 리스트로 변환할 것. 결과: ['banana', 'strawberry', 'watermelon']

**Comment by chiseongan** [comment]
<img width="373" alt="image" src="https://github.com/kyohoonsim/must-know-python/assets/145172742/927af4f8-5f8e-4ad4-afce-d1a28740e2cd">

```python
a = "i Am a boY"
print(a.capitalize())
b = "banana|strawberry|watermelon"
c = b.split("|")
print(c)
```
안치성 완료했습니다

**Comment by Dataholic123** [comment]
<img width="322" alt="image" src="https://github.com/kyohoonsim/must-know-python/assets/145172790/e4dedff5-db03-4e82-a847-03cd3d56735b">

```
a = "i Am a boY"
print(a.lower())
print(a.capitalize())

b = "banana|strawberry|watermelon"
c = b.split("|")
print(c)
```

**Comment by matchapd** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/145172658/9c205a7f-6dc0-40a7-92fe-790f4440ea5d)


>>> print ("i Am a boY".lower())

>>> a = 'banana|strawberry|watermelon'
>>> b = a.split("|")
>>> print(b)

박현욱 완료했습니다.

**Comment by limgw97** [comment]
![image](https://github.com/kyohoonsim/must-know-python/assets/103312768/b3669587-28cf-4c92-a3b5-215b18832f02)
```python
print("i".upper(), "Am a boY".lower())

a = 'banana|strawberry|watermelon'
b = a.split("|")
print(b)
```
임규원 완료했습니다.

**Comment by kwonmms11** [comment]
'''
a="i Am a boY"
print(a.capitalize())
b="banana|strawberry|watermelon" 
c=b.split("|")
print(c)
'''
![image](https://github.com/kyohoonsim/must-know-python/assets/145172696/73ae81cb-c6d3-45c6-bcf0-6f2cf3f5708a)

권민석 완료했습니다.
